name: ded
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.4
  - pip:
      - einops
      - matplotlib
      - opencv-python
      - pudb
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning==2.5.0
      - tensorboard
      - protobuf==4.25
      - omegaconf
      - einops
      - torch-fidelity
      - configargparse
      - timm
      - ninja
      - packaging
      - numpy
      - piq