module:
  target: models.shallow_conv.ShallowConvNet
  params:
    lr: 1e-4
    weight_decay: 0.0
    lr_decay_epoch: 100
    use_fp16: False
    log_interval: 30
    loss_config:
      target: losses.l1lpips.L1LPIPS
      params:
        lpips_weight: 1.0
        l1_weight: 1.0
        ssim_weight: 1.0
        content_weight: 0.2

    in_channels: 3
    embed_dim: 32
    out_channels: 1
    activation: 'torch.nn.GELU'
    last_embed_dim: 4
    num_blocks: 2

data:
  target: datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: datasets.anime.AnimeDataset
      params:
#        root: '/local_datasets/anime_high'
        root: 'D:/datasets/anime_high'
        train: True
        size: [512, 512]
        scale: [ 0.5, 1.0 ]

    validation:
      target: datasets.anime.AnimeDataset
      params:
#        root: '/local_datasets/anime_high'
        root: 'D:/datasets/anime_high'
        train: False
        size: [512, 512]
        scale: [ 0.5, 1.0 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'shallow_conv'
    version: 'vanilla'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/shallow_conv/vanilla'
      filename: 'last'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/shallow_conv/vanilla'
      filename: 'best'
      monitor: 'valid/total_loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 200
  accumulate_grad_batches: 2
  # precision: 'bf16'