module:
  target: models.lpieps.LPIEPS
  params:
    net_type: 'vgg'
    lr: 1e-4
    weight_decay: 0.0
    lr_decay_epoch: 100
    log_interval: 50
    num_blocks: 1
    loss_config:
      target: losses.bce_ranking_loss.BCERankingLoss

data:
  target: datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: datasets.anime_triplet.AnimeTripletDataset
      params:
        root: '/local_datasets/anime'
        # root: 'D:/datasets/anime'
        train: True
        size: [512, 512]
        scale: [ 0.75, 1.0 ]

    validation:
      target: datasets.anime_triplet.AnimeTripletDataset
      params:
        root: '/local_datasets/anime'
        # root: 'D:/datasets/anime'
        train: False
        size: [512, 512]
        scale: [ 0.75, 1.0 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'lpieps/vgg'
    version: '1'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/lpieps/vgg/1'
      filename: 'last'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/lpieps/vgg/1'
      filename: 'best'
      monitor: 'valid/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 200
  accumulate_grad_batches: 1