module:
  target: models.discriminator.Discriminator
  params:
    lr: 2e-5
    weight_decay: 0.0
    log_interval: 50
    loss_config:
      target: losses.prediction_loss.PredictionLoss
      params:
        weight: 1.0

data:
  target: datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 4
    wrap: True
    train:
      target: datasets.edge_granularity.EdgeGranularityDataset
      params:
#        anime_root: '/local_datasets/anime'
#        biped_root: '/local_datasets/BIPED'
        root: 'D:/datasets/'
        train: True
        size: [512, 512]
        scale: [ 0.5, 1.0 ]

    validation:
      target: datasets.edge_granularity.EdgeGranularityDataset
      params:
#        anime_root: '/local_datasets/anime'
#        biped_root: '/local_datasets/BIPED'
        root: 'D:/datasets/'
        train: False
        size: [512, 512]
        scale: [ 0.5, 1.0 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'granularity'
    version: 'discriminator'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/granularity/discriminator'
      filename: 'last'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/granularity/discriminator'
      filename: 'best'
      monitor: 'valid/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 10
  accumulate_grad_batches: 5
  # precision: 'bf16'