module:
  target: models.granularity_prediction.GranularityPredictor
  params:
    lr: 2e-5
    weight_decay: 0.0
    log_interval: 50
    loss_config:
      target: losses.prediction_loss.PredictionLoss
      params:
        abs_weight: 1.0
        bce_weight: 1.0

data:
  target: datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 5
    wrap: True
    train:
      target: datasets.hybrid_for_prediction.HybridExtendDataset
      params:
        anime_root: '/local_datasets/anime'
        biped_root: '/local_datasets/BIPED'
#        anime_root: 'D:/datasets/anime'
#        biped_root: 'D:/datasets/BIPED'
        train: True
        size: [512, 512]
        scale: [ 0.5, 1.0 ]
        color_space: 'rgb'

    validation:
      target: datasets.hybrid_for_prediction.HybridExtendDataset
      params:
        anime_root: '/local_datasets/anime'
        biped_root: '/local_datasets/BIPED'
#        anime_root: 'D:/datasets/anime'
#        biped_root: 'D:/datasets/BIPED'
        train: False
        size: [512, 512]
        scale: [ 0.5, 1.0 ]
        color_space: 'rgb'

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'granularity_prediction'
    version: 'hybrid'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/granularity_prediction/hybrid'
      filename: 'last'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/granularity_prediction/hybrid'
      filename: 'best'
      monitor: 'valid/loss_total'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 200
  accumulate_grad_batches: 1
  # precision: 'bf16'